import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import {access} from 'node:fs/promises';
import * as path from 'node:path';
import {
  build,
  InlineConfig,
  type BuildEnvironmentOptions,
  type Plugin,
} from 'vite';
import {cjsInterop} from 'vite-plugin-cjs-interop';

interface PastoriaCapabilities {
  hasAppRoot: boolean;
  hasServerHandler: boolean;
}

function generateClientEntry({hasAppRoot}: PastoriaCapabilities): string {
  const appImport = hasAppRoot
    ? `import {App} from '#genfiles/router/app_root';`
    : '';
  const appValue = hasAppRoot ? 'App' : 'null';

  return `// Generated by Pastoria.
import {createRouterApp} from '#genfiles/router/router';
${appImport}
import {hydrateRoot} from 'react-dom/client';

async function main() {
  const RouterApp = await createRouterApp();
  hydrateRoot(document, <RouterApp App={${appValue}} />);
}

main();
`;
}

function generateServerEntry({
  hasAppRoot,
  hasServerHandler,
}: PastoriaCapabilities): string {
  const appImport = hasAppRoot
    ? `import {App} from '#genfiles/router/app_root';`
    : '';
  const appValue = hasAppRoot ? 'App' : 'null';

  const serverHandlerImport = hasServerHandler
    ? `import {router as serverHandler} from '#genfiles/router/server_handler';`
    : '';
  const serverHandlerUse = hasServerHandler
    ? '  router.use(serverHandler)'
    : '';

  return `// Generated by Pastoria.
import {JSResource} from '#genfiles/router/js_resource';
import {
  listRoutes,
  router__createAppFromEntryPoint,
  router__loadEntryPoint,
} from '#genfiles/router/router';
import {getSchema} from '#genfiles/schema/schema';
import {Context} from '#genfiles/router/context';
${appImport}
${serverHandlerImport}
import express from 'express';
import {GraphQLSchema, specifiedDirectives} from 'graphql';
import {PastoriaConfig} from 'pastoria-config';
import {createRouterHandler} from 'pastoria-runtime/server';
import type {Manifest} from 'vite';

const schemaConfig = getSchema().toConfig();
const schema = new GraphQLSchema({
  ...schemaConfig,
  directives: [...specifiedDirectives, ...schemaConfig.directives],
});

export function createHandler(
  persistedQueries: Record<string, string>,
  config: Required<PastoriaConfig>,
  manifest?: Manifest,
) {
  const routeHandler = createRouterHandler(
    listRoutes(),
    JSResource.srcOfModuleId,
    router__loadEntryPoint,
    router__createAppFromEntryPoint,
    ${appValue},
    schema,
    (req) => Context.createFromRequest(req),
    persistedQueries,
    config,
    manifest,
  );

  const router = express.Router();
  router.use(routeHandler);
  ${serverHandlerUse}

  return router;
}
`;
}

async function determineCapabilities(): Promise<PastoriaCapabilities> {
  const capabilities: PastoriaCapabilities = {
    hasAppRoot: false,
    hasServerHandler: false,
  };

  async function hasAppRoot() {
    try {
      await access('__generated__/router/app_root.ts');
      capabilities.hasAppRoot = true;
    } catch {}
  }

  async function hasServerHandler() {
    try {
      await access('__generated__/router/server_handler.ts');
      capabilities.hasServerHandler = true;
    } catch {}
  }

  await Promise.all([hasAppRoot(), hasServerHandler()]);
  return capabilities;
}

function pastoriaEntryPlugin(): Plugin {
  const clientEntryModuleId = 'virtual:pastoria-entry-client.tsx';
  const serverEntryModuleId = 'virtual:pastoria-entry-server.tsx';

  return {
    name: 'pastoria-entry',
    resolveId(id) {
      if (id === clientEntryModuleId) {
        return clientEntryModuleId; // Return without \0 prefix so React plugin can see .tsx extension
      } else if (id === serverEntryModuleId) {
        return serverEntryModuleId;
      }
    },
    async load(id) {
      const capabilities = await determineCapabilities();
      if (id === clientEntryModuleId) {
        return generateClientEntry(capabilities);
      } else if (id === serverEntryModuleId) {
        return generateServerEntry(capabilities);
      }
    },
  };
}

export const CLIENT_BUILD: BuildEnvironmentOptions = {
  outDir: 'dist/client',
  rollupOptions: {
    input: 'virtual:pastoria-entry-client.tsx',
  },
};

export const SERVER_BUILD: BuildEnvironmentOptions = {
  outDir: 'dist/server',
  ssr: true,
  rollupOptions: {
    input: 'virtual:pastoria-entry-server.tsx',
  },
};

export function createBuildConfig(
  buildEnv: BuildEnvironmentOptions,
): InlineConfig {
  return {
    appType: 'custom' as const,
    build: {
      ...buildEnv,
      assetsInlineLimit: 0,
      manifest: true,
      ssrManifest: true,
    },
    plugins: [
      pastoriaEntryPlugin(),
      tailwindcss(),
      react({
        babel: {
          plugins: [['babel-plugin-react-compiler', {}], 'relay'],
        },
      }),
      cjsInterop({
        dependencies: ['react-relay', 'react-relay/hooks', 'relay-runtime'],
      }),
    ],
    ssr: {
      noExternal: ['pastoria-runtime'],
    },
  };
}

export async function createBuild() {
  const clientBuild = await build({
    ...createBuildConfig(CLIENT_BUILD),
    configFile: false,
  });

  const serverBuild = await build({
    ...createBuildConfig(SERVER_BUILD),
    configFile: false,
  });
}
