import {createHash} from 'node:crypto';
import * as prettier from 'prettier';
import {SourceFile} from 'ts-morph';

/**
 * Regex to extract the checksum from a generated file's header comment.
 * Matches: @generated-checksum <hex-hash>
 */
const CHECKSUM_REGEX = /@generated-checksum ([a-f0-9]+)/;

/**
 * Computes a SHA-256 checksum of the given content.
 */
function computeChecksum(content: string): string {
  return createHash('sha256').update(content).digest('hex');
}

/**
 * Extracts the checksum from a file's content, if present.
 */
function extractChecksum(content: string): string | null {
  const match = content.match(CHECKSUM_REGEX);
  return match?.[1] ?? null;
}

/**
 * Saves a source file to disk only if its content has changed.
 * Adds a checksum to the file header to enable fast comparison on subsequent runs.
 * Returns true if the file was written, false if skipped due to unchanged content.
 */
export async function saveWithChecksum(
  sourceFile: SourceFile,
): Promise<boolean> {
  const filePath = sourceFile.getFilePath();

  // Get the generated content (without checksum line yet)
  const rawGeneratedContent = sourceFile.getFullText();
  const generatedContent = await prettier.format(rawGeneratedContent, {
    parser: 'typescript',
    singleQuote: true,
  });

  // Compute checksum of the content
  const newChecksum = computeChecksum(generatedContent);

  // Try to read the existing file and extract its checksum
  let existingChecksum: string | null = null;
  try {
    const existingContent = await sourceFile
      .getProject()
      .getFileSystem()
      .readFile(filePath);
    existingChecksum = extractChecksum(existingContent);
  } catch {
    // File doesn't exist yet, will need to write
  }

  // If checksums match, skip writing
  if (existingChecksum === newChecksum) {
    return false;
  }

  // Insert the checksum into the header comment
  // The header comment is the first thing in the file, we insert the checksum on line 2
  const contentWithChecksum = generatedContent.replace(
    '* This file was generated by `pastoria`.',
    `* This file was generated by \`pastoria\`.\n * @generated-checksum ${newChecksum}`,
  );

  // Update the source file content and save
  sourceFile.replaceWithText(contentWithChecksum);
  await sourceFile.save();

  return true;
}
