import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import {Project} from 'ts-morph';
import {
  InlineConfig,
  PluginOption,
  type BuildEnvironmentOptions,
  type Plugin,
} from 'vite';
import {cjsInterop} from 'vite-plugin-cjs-interop';
import {PastoriaExecutionContext} from './generate.js';
import {logger, logInfo} from './logger.js';

function pastoriaEntryPlugin(project: Project): Plugin {
  const clientEntryModuleId = 'virtual:pastoria-entry-client.tsx';
  const serverEntryModuleId = 'virtual:pastoria-entry-server.tsx';
  let shouldGenerateOnBuildStart = false;

  return {
    name: 'pastoria-entry',
    configResolved(config) {
      if (config.command === 'serve') {
        shouldGenerateOnBuildStart = true;
      }
    },
    resolveId(id) {
      if (id === clientEntryModuleId) {
        return clientEntryModuleId; // Return without \0 prefix so React plugin can see .tsx extension
      } else if (id === serverEntryModuleId) {
        return serverEntryModuleId;
      }
    },
    async load(id) {
      if (id === clientEntryModuleId) {
        return generateClientEntry();
      } else if (id === serverEntryModuleId) {
        return generateServerEntry();
      }
    },
    async buildStart() {
      if (!shouldGenerateOnBuildStart) {
        return;
      }

      logInfo('Updating generated files');
      await new PastoriaExecutionContext(project).generatePastoriaArtifacts();
    },
    async watchChange(id, {event}) {
      if (!id.match(/.tsx$/) || id.includes('__generated__')) return;

      if (event === 'create') {
        project.addSourceFileAtPath(id);
      } else if (event === 'delete') {
        project.getSourceFile(id)?.forget();
      } else if (event === 'update') {
        await project.getSourceFile(id)?.refreshFromFileSystem();
      }

      logInfo('Updating generated files');
      await new PastoriaExecutionContext(project).generatePastoriaArtifacts();
    },
  };
}

export const CLIENT_BUILD: BuildEnvironmentOptions = {
  outDir: 'dist/client',
  rollupOptions: {
    input: 'virtual:pastoria-entry-client.tsx',
  },
};

export const SERVER_BUILD: BuildEnvironmentOptions = {
  outDir: 'dist/server',
  ssr: true,
  rollupOptions: {
    input: 'virtual:pastoria-entry-server.tsx',
  },
};

export function createBuildConfig(
  project: Project,
  buildEnv: BuildEnvironmentOptions,
): InlineConfig {
  return {
    appType: 'custom' as const,
    customLogger: logger,
    build: {
      ...buildEnv,
      assetsInlineLimit: 0,
      manifest: true,
      ssrManifest: true,
    },
    plugins: [
      pastoriaEntryPlugin(project),
      tailwindcss() as PluginOption,
      react({
        babel: {
          plugins: [['babel-plugin-react-compiler', {}], 'relay'],
        },
      }),
      cjsInterop({
        dependencies: ['react-relay', 'react-relay/hooks', 'relay-runtime'],
      }),
    ],
    ssr: {
      noExternal: ['pastoria-runtime'],
    },
  };
}

function generateClientEntry(): string {
  return `// Generated by Pastoria.
import {createRouterApp} from '#genfiles/router/router';
import App from '#pastoria/app';
import {hydrateRoot} from 'react-dom/client';

async function main() {
  const RouterApp = await createRouterApp();
  hydrateRoot(document, <RouterApp App={App} />);
}

main();
`;
}

function generateServerEntry(): string {
  return `// Generated by Pastoria.
import {JSResource} from '#genfiles/router/js_resource';
import {
  listRoutes,
  router__createAppFromEntryPoint,
  router__loadEntryPoint,
} from '#genfiles/router/router';
import {router as serverRouter} from '#genfiles/router/server';
import App from '#pastoria/app';
import environment from '#pastoria/environment';
import express from 'express';
import {createRouterHandler} from 'pastoria-runtime/server';
import type {Manifest} from 'vite';

export function createHandler(
  persistedQueries: Record<string, string>,
  manifest?: Manifest,
) {
  const routeHandler = createRouterHandler(
    listRoutes(),
    JSResource.srcOfModuleId,
    router__loadEntryPoint,
    router__createAppFromEntryPoint,
    App,
    environment,
    persistedQueries,
    manifest,
  );

  const router = express.Router();
  router.use(routeHandler);
  router.use(serverRouter)

  return router;
}
`;
}
