/*
 * This file was generated by `pastoria`.
 * @generated-checksum ae5127744a4d49e8d42cdacbd350c735dfff7371ea358fcd01c2f74f1f790d4f
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/hello/[name]/banner';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import banner_HelloBannerQueryParameters from '#genfiles/queries/banner_HelloBannerQuery$parameters';
import type {
  banner_HelloBannerQuery,
  banner_HelloBannerQuery$variables,
} from '#genfiles/queries/banner_HelloBannerQuery.graphql';

const schema = z.object({});

const entrypoint: EntryPoint<
  ModuleType<'/hello/[name]#banner'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/hello/[name]#banner'),
  getPreloadProps(variables) {
    return {
      queries: {
        helloBannerRef: {
          parameters: banner_HelloBannerQueryParameters,
          variables: {},
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    helloBannerRef: (
      variables: banner_HelloBannerQuery$variables,
    ) => ThinQueryParams<banner_HelloBannerQuery>;
  };
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type PreloadPropsHelpers,
};
