/*
 * This file was generated by `pastoria`.
 * @generated-checksum 9969427d315bbb95adc805c4fbda4b75c2947276aee8afb168962ef6af1a5d48
 * Do not modify this file directly.
 */
import type { EntryPoints, Queries } from '../../pastoria/hello/[name]/page';
import { EntryPoint, ThinQueryParams } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_HelloQueryParameters from '#genfiles/queries/page_HelloQuery$parameters';
import type {
  page_HelloQuery,
  page_HelloQuery$variables,
} from '#genfiles/queries/page_HelloQuery.graphql';

const schema = z.object({
  name: z.string(),
  q: z.nullish(z.string()),
});
const entrypoint: EntryPoint<
  ModuleType<'/hello/[name]'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/hello/[name]'),
  getPreloadProps($variables) {
    return (({ queries, variables }) => {
      return {
        queries: {
          nameQuery: queries.nameQuery({ name: variables.name }),
        },
        entryPoints: {
          helloBanner: null!,
          searchResults: null!,
        },
      };
    })({
      variables: $variables,
      queries: {
        ['nameQuery']: (variables) => ({
          parameters: page_HelloQueryParameters,
          variables,
        }),
      },
    } satisfies PreloadPropsHelpers);
  },
};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    nameQuery: (
      variables: page_HelloQuery$variables,
    ) => ThinQueryParams<page_HelloQuery>;
  };
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type PreloadPropsHelpers,
};
