/*
 * This file was generated by `pastoria`.
 * @generated-checksum 2154633e901cbd906a8264169091d026d4e78cf54cb3b0210a801289dd487259
 * Do not modify this file directly.
 */
import type { EntryPoints, Queries } from '../../pastoria/hello/[name]/page';
import { EntryPoint, ThinQueryParams } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_HelloQueryParameters from '#genfiles/queries/page_HelloQuery$parameters';
import type {
  page_HelloQuery,
  page_HelloQuery$variables,
} from '#genfiles/queries/page_HelloQuery.graphql';

const schema = z.object({
  name: z.string(),
  q: z.nullish(z.string()),
});
const entrypoint: EntryPoint<
  ModuleType<'#pastoria/hello/[name]/page'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('#pastoria/hello/[name]/page'),
  getPreloadProps($variables) {
    return (({ queries, variables }) => {
      return {
        queries: {
          nameQuery: queries.nameQuery({ name: variables.name }),
        },
      };
    })({
      variables: $variables,
      queries: {
        ['nameQuery']: (variables) => ({
          parameters: page_HelloQueryParameters,
          variables,
        }),
      },
    } satisfies PreloadPropParams);
  },
};

type PreloadPropParams = {
  variables: z.output<typeof schema>;
  queries: {
    nameQuery: (
      variables: page_HelloQuery$variables,
    ) => ThinQueryParams<page_HelloQuery>;
  };
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type PreloadPropParams,
};
