/*
 * This file was generated by `pastoria`.
 * @generated-checksum ce85f791c91833d17f8d6b23a9374f7a9795cc32c17fc76e9814470aa69d86f9
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/hello/[name]/banner';
import { EntryPoint, ThinQueryParams } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import banner_HelloBannerQueryParameters from '#genfiles/queries/banner_HelloBannerQuery$parameters';
import type {
  banner_HelloBannerQuery,
  banner_HelloBannerQuery$variables,
} from '#genfiles/queries/banner_HelloBannerQuery.graphql';

const schema = z.object({});
const entrypoint: EntryPoint<
  ModuleType<'/hello/[name]#banner'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/hello/[name]#banner'),
  getPreloadProps(variables) {
    return {
      queries: {
        helloBannerRef: {
          parameters: banner_HelloBannerQueryParameters,
          variables: {},
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    helloBannerRef: (
      variables: banner_HelloBannerQuery$variables,
    ) => ThinQueryParams<banner_HelloBannerQuery>;
  };
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type PreloadPropsHelpers,
};
