/*
 * This file was generated by `pastoria`.
 * @generated-checksum 17d6e6eb36f25d8b5a789d807320c90388b1ed805a0f972ea0596ef1a66b7e5e
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/search/page';
import { EntryPoint, ThinQueryParams } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_GreetQueryParameters from '#genfiles/queries/page_GreetQuery$parameters';
import page_SearchResultsQueryParameters from '#genfiles/queries/page_SearchResultsQuery$parameters';
import type {
  page_GreetQuery,
  page_GreetQuery$variables,
} from '#genfiles/queries/page_GreetQuery.graphql';
import type {
  page_SearchResultsQuery,
  page_SearchResultsQuery$variables,
} from '#genfiles/queries/page_SearchResultsQuery.graphql';

const schema = z.object({
  q: z.pipe(
    z.nullish(z.pipe(z.string(), z.transform(decodeURIComponent))),
    z.transform((s) => (s == null ? undefined : s)),
  ),
});
const entrypoint: EntryPoint<ModuleType<'/search'>, z.output<typeof schema>> = {
  root: JSResource.fromModuleId('/search'),
  getPreloadProps(variables) {
    return {
      queries: {
        bannerMessage: {
          parameters: page_GreetQueryParameters,
          variables: {},
        },
        searchResults: {
          parameters: page_SearchResultsQueryParameters,
          variables: { q: variables.q },
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    bannerMessage: (
      variables: page_GreetQuery$variables,
    ) => ThinQueryParams<page_GreetQuery>;
    searchResults: (
      variables: page_SearchResultsQuery$variables,
    ) => ThinQueryParams<page_SearchResultsQuery>;
  };
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type PreloadPropsHelpers,
};
