/*
 * This file was generated by `pastoria`.
 * @generated-checksum 5f4975cc50d24bc9923a9903d7003fbf9873e3273f46b7618519c57016e2abc4
 * Do not modify this file directly.
 */
import type { Queries } from '#pastoria/search/page';
import { EntryPoint } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_GreetQueryParameters from '#genfiles/queries/page_GreetQuery$parameters';
import page_SearchResultsQueryParameters from '#genfiles/queries/page_SearchResultsQuery$parameters';

const schema = z.object({
  q: z.pipe(
    z.nullish(z.pipe(z.string(), z.transform(decodeURIComponent))),
    z.transform((s) => (s == null ? undefined : s)),
  ),
});
const entrypoint: EntryPoint<
  ModuleType<'route(/search)'>,
  { params: Record<string, any>; schema: typeof schema }
> = {
  root: JSResource.fromModuleId('route(/search)'),
  getPreloadProps({ params, schema }) {
    const variables = schema.parse(params);
    return {
      queries: {
        bannerMessage: {
          parameters: page_GreetQueryParameters,
          variables: {},
        },
        searchResults: {
          parameters: page_SearchResultsQueryParameters,
          variables: { q: variables.q },
        },
      },
      entryPoints: {},
    };
  },
};
type EntryPoints = {};

export { entrypoint, schema, type EntryPoints, type Queries };
