/*
 * This file was generated by `pastoria`.
 * @generated-checksum 17aa20b626d497a803fe80f3f05da7ce3d850e1c64c0c5f32311bc0faff028a5
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/search/page';
import { EntryPoint } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_GreetQueryParameters from '#genfiles/queries/page_GreetQuery$parameters';
import page_SearchResultsQueryParameters from '#genfiles/queries/page_SearchResultsQuery$parameters';

const schema = z.object({
  q: z.pipe(
    z.nullish(z.pipe(z.string(), z.transform(decodeURIComponent))),
    z.transform((s) => (s == null ? undefined : s)),
  ),
});
const entrypoint: EntryPoint<
  ModuleType<'#pastoria/search/page'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('#pastoria/search/page'),
  getPreloadProps(variables) {
    return {
      queries: {
        bannerMessage: {
          parameters: page_GreetQueryParameters,
          variables: {},
        },
        searchResults: {
          parameters: page_SearchResultsQueryParameters,
          variables: { q: variables.q },
        },
      },
      entryPoints: {},
    };
  },
};
type EntryPoints = {};

export { entrypoint, schema, type EntryPoints, type Queries };
