/*
 * This file was generated by `pastoria`.
 * @generated-checksum 7bf616b7e3b4c083f6575ea9146410ea28b8fc7a15d90a8aaf8a5b17fb18c89c
 * Do not modify this file directly.
 */
import type { EntryPointProps, PreloadProps } from 'react-relay/hooks';
import type { z } from 'zod/v4-mini';
import type {
  Queries as search_page_EP_Queries,
  EntryPoints as search_page_EP_EntryPoints,
  RuntimeProps as search_page_EP_RuntimeProps,
  ExtraProps as search_page_EP_ExtraProps,
  schema as search_page_EP_schema,
  PreloadPropsHelpers as search_page_EP_PreloadPropsHelpers,
} from './search_page.entrypoint';
import type {
  Queries as hello_$name_banner_EP_Queries,
  EntryPoints as hello_$name_banner_EP_EntryPoints,
  RuntimeProps as hello_$name_banner_EP_RuntimeProps,
  ExtraProps as hello_$name_banner_EP_ExtraProps,
  schema as hello_$name_banner_EP_schema,
  PreloadPropsHelpers as hello_$name_banner_EP_PreloadPropsHelpers,
} from './hello_$name_banner.entrypoint';
import type {
  Queries as hello_$name_page_EP_Queries,
  EntryPoints as hello_$name_page_EP_EntryPoints,
  RuntimeProps as hello_$name_page_EP_RuntimeProps,
  ExtraProps as hello_$name_page_EP_ExtraProps,
  schema as hello_$name_page_EP_schema,
  PreloadPropsHelpers as hello_$name_page_EP_PreloadPropsHelpers,
} from './hello_$name_page.entrypoint';
import type {
  Queries as hello_$name_results_EP_Queries,
  EntryPoints as hello_$name_results_EP_EntryPoints,
  RuntimeProps as hello_$name_results_EP_RuntimeProps,
  ExtraProps as hello_$name_results_EP_ExtraProps,
  schema as hello_$name_results_EP_schema,
  PreloadPropsHelpers as hello_$name_results_EP_PreloadPropsHelpers,
} from './hello_$name_results.entrypoint';

declare global {
  type PastoriaRouteName =
    | '/search'
    | '/hello/[name]#banner'
    | '/hello/[name]'
    | '/hello/[name]#results';

  type PastoriaPageQueries = {
    ['/search']: search_page_EP_Queries;
    ['/hello/[name]#banner']: hello_$name_banner_EP_Queries;
    ['/hello/[name]']: hello_$name_page_EP_Queries;
    ['/hello/[name]#results']: hello_$name_results_EP_Queries;
  };

  type PastoriaPageEntryPoints = {
    ['/search']: search_page_EP_EntryPoints;
    ['/hello/[name]#banner']: hello_$name_banner_EP_EntryPoints;
    ['/hello/[name]']: hello_$name_page_EP_EntryPoints;
    ['/hello/[name]#results']: hello_$name_results_EP_EntryPoints;
  };

  type PastoriaPageRuntimeProps = {
    ['/search']: search_page_EP_RuntimeProps;
    ['/hello/[name]#banner']: hello_$name_banner_EP_RuntimeProps;
    ['/hello/[name]']: hello_$name_page_EP_RuntimeProps;
    ['/hello/[name]#results']: hello_$name_results_EP_RuntimeProps;
  };

  type PastoriaPageExtraProps = {
    ['/search']: search_page_EP_ExtraProps;
    ['/hello/[name]#banner']: hello_$name_banner_EP_ExtraProps;
    ['/hello/[name]']: hello_$name_page_EP_ExtraProps;
    ['/hello/[name]#results']: hello_$name_results_EP_ExtraProps;
  };

  type PastoriaPageProps<T extends PastoriaRouteName> = EntryPointProps<
    PastoriaPageQueries[T],
    PastoriaPageEntryPoints[T],
    PastoriaPageRuntimeProps[T],
    PastoriaPageExtraProps[T]
  >;

  type PastoriaPreloadPropsParams = {
    ['/search']: z.output<typeof search_page_EP_schema>;
    ['/hello/[name]#banner']: z.output<typeof hello_$name_banner_EP_schema>;
    ['/hello/[name]']: z.output<typeof hello_$name_page_EP_schema>;
    ['/hello/[name]#results']: z.output<typeof hello_$name_results_EP_schema>;
  };

  type PastoriaPreloadPropsHelpers = {
    ['/search']: search_page_EP_PreloadPropsHelpers;
    ['/hello/[name]#banner']: hello_$name_banner_EP_PreloadPropsHelpers;
    ['/hello/[name]']: hello_$name_page_EP_PreloadPropsHelpers;
    ['/hello/[name]#results']: hello_$name_results_EP_PreloadPropsHelpers;
  };

  type GetPreloadProps<R extends PastoriaRouteName> = (
    params: PastoriaPreloadPropsHelpers[R],
  ) => PreloadProps<
    PastoriaPreloadPropsParams[R],
    PastoriaPageQueries[R],
    PastoriaPageEntryPoints[R],
    PastoriaPageExtraProps[R]
  >;

  type ModuleParams<T extends PastoriaRouteName> =
    PastoriaPreloadPropsParams[T];
}
