/*
 * This file was generated by `pastoria`.
 * Do not modify this file directly.
 *
 * Type definitions for filesystem-based routing.
 */

import type {EntryPoint, EntryPointComponent, EntryPointProps} from 'react-relay/hooks';

import type {searchResults_Query} from '#genfiles/queries/searchResults_Query.graphql';
import type {HelloBannerQuery} from '#genfiles/queries/HelloBannerQuery.graphql';
import type {helloResults_CityResultsQuery} from '#genfiles/queries/helloResults_CityResultsQuery.graphql';
import type {page_HelloQuery} from '#genfiles/queries/page_HelloQuery.graphql';

import type {searchResults_Query$variables} from '#genfiles/queries/searchResults_Query.graphql';
import type {page_HelloQuery$variables} from '#genfiles/queries/page_HelloQuery.graphql';
import type {HelloBannerQuery$variables} from '#genfiles/queries/HelloBannerQuery.graphql';
import type {helloResults_CityResultsQuery$variables} from '#genfiles/queries/helloResults_CityResultsQuery.graphql';

// Route type aliases - nested entry points (leaf nodes)
type RouteRoot_search_results = { queries: { citiesQueryRef: searchResults_Query }; entryPoints: {} };
type RouteHello$name_hello_banner = { queries: { helloBannerRef: HelloBannerQuery }; entryPoints: {} };
type RouteHello$name_hello_results = { queries: { citiesQuery: helloResults_CityResultsQuery }; entryPoints: {} };

// Route type aliases - main pages
type RouteRoot = { queries: {}; entryPoints: { search_results: EntryPoint<EntryPointComponent<RouteRoot_search_results['queries'], RouteRoot_search_results['entryPoints'], {}, {}>, {}> } };
type RouteHello$name = { queries: { nameQuery: page_HelloQuery }; entryPoints: { hello_banner?: EntryPoint<EntryPointComponent<RouteHello$name_hello_banner['queries'], RouteHello$name_hello_banner['entryPoints'], {}, {}>, {}>; hello_results: EntryPoint<EntryPointComponent<RouteHello$name_hello_results['queries'], RouteHello$name_hello_results['entryPoints'], {}, {}>, {}> } };

/**
 * Map of route paths to their query types.
 * Nested entry points use the format: '/route#entryPointName'
 */
export interface PageQueryMap {
  '/': RouteRoot;
  '/#search_results': RouteRoot_search_results;
  '/hello/[name]': RouteHello$name;
  '/hello/[name]#hello_banner': RouteHello$name_hello_banner;
  '/hello/[name]#hello_results': RouteHello$name_hello_results;
}

// Query helper type aliases for each route
type QueryHelpers_RouteRoot = {};
type QueryHelpers_RouteHello$name = { nameQuery: (variables: page_HelloQuery$variables) => { parameters: unknown; variables: page_HelloQuery$variables } };

// Entry point helper type aliases for each route
type EntryPointHelpers_RouteRoot = { search_results: (variables: searchResults_Query$variables) => { entryPointParams: Record<string, never>; entryPoint: EntryPoint<EntryPointComponent<RouteRoot_search_results['queries'], RouteRoot_search_results['entryPoints'], {}, {}>, {}> } };
type EntryPointHelpers_RouteHello$name = { hello_banner: (variables: HelloBannerQuery$variables) => { entryPointParams: Record<string, never>; entryPoint: EntryPoint<EntryPointComponent<RouteHello$name_hello_banner['queries'], RouteHello$name_hello_banner['entryPoints'], {}, {}>, {}> } | undefined; hello_results: (variables: helloResults_CityResultsQuery$variables) => { entryPointParams: Record<string, never>; entryPoint: EntryPoint<EntryPointComponent<RouteHello$name_hello_results['queries'], RouteHello$name_hello_results['entryPoints'], {}, {}>, {}> } };

/**
 * Query helper functions for a route.
 * Each helper takes typed variables and returns {parameters, variables} for Relay.
 */
export interface QueryHelpersMap {
  '/': QueryHelpers_RouteRoot;
  '/hello/[name]': QueryHelpers_RouteHello$name;
}

export type QueryHelpersForRoute<R extends string> = R extends keyof QueryHelpersMap
  ? QueryHelpersMap[R]
  : {};

/**
 * Entry point helper functions for a route.
 * Each helper takes typed variables and returns the nested entry point configuration.
 */
export interface EntryPointHelpersMap {
  '/': EntryPointHelpers_RouteRoot;
  '/hello/[name]': EntryPointHelpers_RouteHello$name;
}

export type EntryPointHelpersForRoute<R extends string> = R extends keyof EntryPointHelpersMap
  ? EntryPointHelpersMap[R]
  : {};

/**
 * Props type for a page component at the given route.
 * Uses EntryPointProps to transform raw query types to PreloadedQuery<...>.
 *
 * @example
 * ```typescript
 * // Main page
 * export default function BlogPosts({ queries }: PageProps<'/posts'>) {
 *   const data = usePreloadedQuery(query, queries.posts);
 * }
 *
 * // Nested entry point
 * export default function Sidebar({ queries }: PageProps<'/posts#sidebar'>) {
 *   const data = usePreloadedQuery(query, queries.sidebarData);
 * }
 * ```
 */
export type PageProps<R extends keyof PageQueryMap> = EntryPointProps<
  PageQueryMap[R]['queries'],
  PageQueryMap[R]['entryPoints'],
  {},
  {}
>;

/**
 * Return type for getPreloadProps in entrypoint.ts files.
 * This type matches the structure expected by Relay's loadEntryPoint.
 *
 * @example
 * ```typescript
 * export default function getPreloadProps({
 *   params,
 *   queries,
 *   entryPoints,
 * }: EntryPointParams<'/posts'>): PreloadPropsForRoute<'/posts'> {
 *   return {
 *     queries: {
 *       postsQuery: queries.postsQuery(params),
 *     },
 *     entryPoints: {
 *       sidebar: entryPoints.sidebar({}),
 *     },
 *   };
 * }
 * ```
 */
export type PreloadPropsForRoute<R extends keyof PageQueryMap> = {
  queries: {
    [K in keyof PageQueryMap[R]['queries']]: {
      parameters: unknown;
      variables: unknown;
    };
  };
  entryPoints: PageQueryMap[R]['entryPoints'] extends Record<string, never>
    ? undefined
    : {
        [K in keyof PageQueryMap[R]['entryPoints']]: {
          entryPointParams: unknown;
          entryPoint: unknown;
        };
      };
};
