minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@oxfmt/*'
  - '@oxlint/*'
  - '@oxlint-tsgolint/*'
  - '@voidzero-dev/*'
  - oxfmt
  - oxlint
  - oxlint-tsgolint
  - vite
  - vite-plus

packages:
  - docs
  - examples/*
  - packages/*

catalog:
  '@stylexjs/stylex': ^0.18.1
  '@tailwindcss/vite': ^4.2.1
  '@types/cookie-parser': ^1.4.9
  '@types/express': ^5.0.3
  '@types/node': ^22.12.0
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@types/react-relay': ^18.2.1
  '@types/relay-runtime': ^19.0.2
  babel-plugin-relay: ^20.1.1
  commander: ^14.0.1
  cookie-parser: ^1.4.7
  dotenv: ^16.6.1
  express: ^5.1.0
  graphql: 17.0.0-alpha.9
  grats: ^0.0.33
  picocolors: ^1.1.1
  react: ^19.2.0
  react-dom: ^19.2.0
  react-relay: ^20.1.1
  relay-compiler: ^20.1.1
  relay-runtime: ^20.1.1
  tailwindcss: ^4.1.14
  typescript: ^6.0.2
  vite: ^8.0.5
  vite-plus: ^0.1.16
  vitest: ^4.1.2
  zod: ^3.25.76

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - core-js-pure
  - esbuild
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
  vitepress>vite: ^8
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
