/*
 * This file was generated by `pastoria`.
 * @generated-checksum 11bfe3efe8fa03cd61bf532d49890c0b44d47712bc3e8333e1c07486a6e7c277
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/details/[name]/page';
import { EntryPoint } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_DetailsQueryParameters from '#genfiles/queries/page_DetailsQuery$parameters';

const schema = z.object({
  name: z.pipe(z.string(), z.transform(decodeURIComponent)),
});
const entrypoint: EntryPoint<
  ModuleType<'#pastoria/details/[name]/page'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('#pastoria/details/[name]/page'),
  getPreloadProps(variables) {
    return {
      queries: {
        details: {
          parameters: page_DetailsQueryParameters,
          variables: { name: variables.name },
        },
      },
      entryPoints: {},
    };
  },
};
type EntryPoints = {};

export { entrypoint, schema, type EntryPoints, type Queries };
