/*
 * This file was generated by `pastoria`.
 * @generated-checksum 077f98517659199e20069a6313eda99befa89d53cb67f3d6d04eba4788329bbd
 * Do not modify this file directly.
 */
import type { Queries } from '#pastoria/details/[name]/page';
import { EntryPoint } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_DetailsQueryParameters from '#genfiles/queries/page_DetailsQuery$parameters';

const schema = z.object({
  name: z.pipe(z.string(), z.transform(decodeURIComponent)),
});
const entrypoint: EntryPoint<
  ModuleType<'route(/details/[name])'>,
  { params: Record<string, unknown> }
> = {
  root: JSResource.fromModuleId('route(/details/[name])'),
  getPreloadProps({ params }) {
    const variables = schema.parse(params);
    return {
      queries: {
        details: {
          parameters: page_DetailsQueryParameters,
          variables: { name: variables.name },
        },
      },
      entryPoints: {},
    };
  },
};
type EntryPoints = {};

export { entrypoint, schema, type EntryPoints, type Queries };
