/*
 * This file was generated by `pastoria`.
 * @generated-checksum 26fccc94c66cd981d65ee0cadb1bc8fcc88cb0e4077eacc6eee65cb86930d4c1
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/details/[name]/page';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_DetailsQueryParameters from '#genfiles/queries/page_DetailsQuery$parameters';
import type {
  page_DetailsQuery,
  page_DetailsQuery$variables,
} from '#genfiles/queries/page_DetailsQuery.graphql';

const schema = z.object({
  name: z.pipe(z.string(), z.transform(decodeURIComponent)),
});

const entrypoint: EntryPoint<
  ModuleType<'/details/[name]'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/details/[name]'),
  getPreloadProps(variables) {
    return {
      queries: {
        details: {
          parameters: page_DetailsQueryParameters,
          variables: { name: variables.name },
        },
      },
      entryPoints: {},
    };
  },
};

type EntryPoints = {};

type RuntimeProps = { pathname: string; searchParams: URLSearchParams };

type ExtraProps = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    details: (
      variables: page_DetailsQuery$variables,
    ) => ThinQueryParams<page_DetailsQuery>;
  };
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
