/*
 * This file was generated by `pastoria`.
 * @generated-checksum 9f80a6300092b50c61635006be7e90c620132dae3145573fae182bb5e3cdd064
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/details/[name]/page';
import { EntryPoint } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_DetailsQueryParameters from '#genfiles/queries/page_DetailsQuery$parameters';

const schema = z.object({
  name: z.pipe(z.string(), z.transform(decodeURIComponent)),
});
const entrypoint: EntryPoint<
  ModuleType<'#pastoria/details/[name]/page'>,
  { params: Record<string, unknown> }
> = {
  root: JSResource.fromModuleId('#pastoria/details/[name]/page'),
  getPreloadProps({ params }) {
    const variables = schema.parse(params);
    return {
      queries: {
        details: {
          parameters: page_DetailsQueryParameters,
          variables: { name: variables.name },
        },
      },
      entryPoints: {},
    };
  },
};
type EntryPoints = {};

export { entrypoint, schema, type EntryPoints, type Queries };
