/*
 * This file was generated by `pastoria`.
 * @generated-checksum 23099ea0846eb89eabc01185b6c3757db8de75240a760cc768ac7628ceb78667
 * Do not modify this file directly.
 */
import page_DetailsQueryParameters from "#genfiles/queries/page_DetailsQuery$parameters";
import type { Queries } from "#pastoria/details/[name]/page";
import { EntryPoint } from "react-relay/hooks";
import { z } from "zod/v4-mini";
import { JSResource, ModuleType } from "./js_resource";

const schema = z.object({name: z.pipe(z.string(), z.transform(decodeURIComponent))});

const entrypoint: EntryPoint<ModuleType<'route(/details/[name])'>, {params: unknown}> = {
  root: JSResource.fromModuleId('route(/details/[name])'),
  getPreloadProps({params}) {
    const variables = schema.parse(params);
    return {
      queries: {
        details: {
          parameters: page_DetailsQueryParameters,
          variables: {name: variables.name},
        },
      },
      entryPoints: undefined,
    };
  },
};
type EntryPoints = {};

export {entrypoint, schema, type EntryPoints, type Queries};

