/*
 * This file was generated by `pastoria`.
 * @generated-checksum e4e3c981d5bd5d2a5c550bb8c08e2c367a1b338ad9f5786c08bf64ccae325a93
 * Do not modify this file directly.
 */
import type { Queries } from "#pastoria/details/[name]/page";
import { EntryPoint } from "react-relay/hooks";
import { z } from "zod/v4-mini";
import { JSResource, ModuleType } from "./js_resource";
import page_DetailsQueryParameters from "#genfiles/queries/page_DetailsQuery$parameters";

const schema = z.object({
  name: z.pipe(z.string(), z.transform(decodeURIComponent)),
});
const entrypoint: EntryPoint<
  ModuleType<"route(/details/[name])">,
  { params: Record<string, any>; schema: typeof schema }
> = {
  root: JSResource.fromModuleId("route(/details/[name])"),
  getPreloadProps({ params, schema }) {
    const variables = schema.parse(params);
    return {
      queries: {
        details: {
          parameters: page_DetailsQueryParameters,
          variables: { name: variables.name },
        },
      },
      entryPoints: {},
    };
  },
};
type EntryPoints = {};

export { entrypoint, schema, type EntryPoints, type Queries };
