/*
 * This file was generated by `pastoria`.
 * @generated-checksum 98e19d0811e27f3d3fa564ae176c1855cdd644f12a2e1058a6cfa9efa6c1a875
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/hello/[name]/page';
import { EntryPoint, ThinQueryParams } from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_HelloQueryParameters from '#genfiles/queries/page_HelloQuery$parameters';
import type {
  page_HelloQuery,
  page_HelloQuery$variables,
} from '#genfiles/queries/page_HelloQuery.graphql';

const schema = z.object({
  name: z.pipe(z.string(), z.transform(decodeURIComponent)),
});
const entrypoint: EntryPoint<
  ModuleType<'#pastoria/hello/[name]/page'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('#pastoria/hello/[name]/page'),
  getPreloadProps($variables) {
    return (({ variables, queries }) => {
      return {
        queries: {
          hello: queries.hello({ name: variables.name }),
        },
      };
    })({
      variables: $variables,
      queries: {
        ['hello']: (variables) => ({
          parameters: page_HelloQueryParameters,
          variables,
        }),
      },
    } satisfies PreloadPropParams);
  },
};

type EntryPoints = {};

type PreloadPropParams = {
  variables: z.output<typeof schema>;
  queries: {
    hello: (
      variables: page_HelloQuery$variables,
    ) => ThinQueryParams<page_HelloQuery>;
  };
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type PreloadPropParams,
};
