/*
 * This file was generated by `pastoria`.
 * @generated-checksum 5854a413bfec0f0ad2671c31c58249ab38831449671df4b12c34fe93485acb0a
 * Do not modify this file directly.
 */
import type { Queries } from '../../pastoria/hello/[name]/page';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_HelloQueryParameters from '#genfiles/queries/page_HelloQuery$parameters';
import type {
  page_HelloQuery,
  page_HelloQuery$variables,
} from '#genfiles/queries/page_HelloQuery.graphql';

const schema = z.object({
  name: z.pipe(z.string(), z.transform(decodeURIComponent)),
});

const entrypoint: EntryPoint<
  ModuleType<'/hello/[name]'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/hello/[name]'),
  getPreloadProps($variables) {
    return (({ variables, queries }) => {
      return {
        queries: {
          hello: queries.hello({ name: variables.name }),
        },
      };
    })({
      variables: $variables,
      queries: {
        ['hello']: (variables) => ({
          parameters: page_HelloQueryParameters,
          variables,
        }),
      },
      entryPoints: {},
    } satisfies PreloadPropsHelpers);
  },
};

type EntryPoints = {};

type RuntimeProps = { pathname: string; searchParams: URLSearchParams };

type ExtraProps = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    hello: (
      variables: page_HelloQuery$variables,
    ) => ThinQueryParams<page_HelloQuery>;
  };
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
