/*
 * This file was generated by `pastoria`.
 * @generated-checksum ed217dd3eafe00475bc6f4b66cba62c31b41b690a885b53348393f736ed7d719
 * Do not modify this file directly. Instead, edit the template at js_resource.ts.
 */

import type {JSResourceReference} from 'react-relay/hooks';

type ResourceConf = typeof RESOURCE_CONF;
const RESOURCE_CONF = {
  "route(/hello/:name)": {
      src: "src/hello_world.tsx",
      loader: () => import("../../src/hello_world").then(m => m.HelloWorldPage)
    },
  "m#home": {
      src: "src/home.tsx",
      loader: () => import("../../src/home").then(m => m.HomePage)
    },
  "route(/cool)": {
      src: "pastoria/cool/page.tsx",
      loader: () => import("#pastoria/cool/page").then(m => m.default),
    }
} as const;

type ModuleId = keyof ResourceConf;
export type ModuleType<M extends ModuleId> = Awaited<
  ReturnType<ResourceConf[M]['loader']>
>;

export class JSResource<M extends ModuleId>
  implements JSResourceReference<ModuleType<M>>
{
  static srcOfModuleId(id: string): string | null {
    return RESOURCE_CONF[id as ModuleId].src;
  }

  private static readonly resourceCache = new Map<ModuleId, JSResource<any>>();
  static fromModuleId<M extends ModuleId>(moduleId: M) {
    if (JSResource.resourceCache.has(moduleId)) {
      return JSResource.resourceCache.get(moduleId)!;
    }

    const resource = new JSResource(moduleId);
    JSResource.resourceCache.set(moduleId, resource);
    return resource;
  }

  private constructor(private readonly moduleId: M) {}
  private modulePromiseCache: Promise<ModuleType<M>> | null = null;
  private moduleCache: ModuleType<M> | null = null;

  getModuleId(): string {
    return this.moduleId;
  }

  getModuleIfRequired(): ModuleType<M> | null {
    return this.moduleCache;
  }

  async load(): Promise<ModuleType<M>> {
    if (this.modulePromiseCache == null) {
      this.modulePromiseCache = RESOURCE_CONF[this.moduleId]
        .loader()
        .then((m) => {
          this.moduleCache = m as ModuleType<M>;
          return this.moduleCache;
        });
    }

    return await this.modulePromiseCache;
  }
}
