/*
 * This file was generated by `pastoria`.
 * @generated-checksum bd5d0117e09395c3d6e8bfcd4871f78b8276e5d9760c63b6f708c48aecef06b8
 * Do not modify this file directly.
 */
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';

const schema = z.object({});

const entrypoint: EntryPoint<ModuleType<'/'>, z.output<typeof schema>> = {
  root: JSResource.fromModuleId('/'),
  getPreloadProps(variables) {
    return {
      queries: {},
      entryPoints: {},
    };
  },
};

type Queries = {};

type EntryPoints = {};

type RuntimeProps = { pathname: string; searchParams: URLSearchParams };

type ExtraProps = {};

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {};
  entryPoints: {};
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
