/*
 * This file was generated by `pastoria`.
 * @generated-checksum 048b2f3ed37478cdd8c154eb6c3c0d6f273b5e001ffc93ea0bb98f626cf8d864
 * Do not modify this file directly. Instead, edit the template at server.ts.
 */

import express from 'express';
import { default as e0 } from '../../pastoria/api/greet/[name]/route';

export const router = express.Router();
router.use('/api/greet/:name', e0);
