/*
 * This file was generated by `pastoria`.
 * @generated-checksum b680113bfb4fba07a561baf6d1c90d6134c63bcc181ad247371a733789526d9b
 * Do not modify this file directly. Instead, edit the template at server.ts.
 */

import express from "express";
import { default as e0 } from "../../pastoria/api/greet/[name]/route";

export const router = express.Router();
router.use("/api/greet/:name", e0);
