/*
 * This file was generated by `pastoria`.
 * @generated-checksum bb7d2959c892420aab751850ed5939d7d6e809d29d23f7bee16a085bc781161b
 * Do not modify this file directly.
 */
import type { EntryPointProps, PreloadProps } from 'react-relay/hooks';
import type { z } from 'zod/v4-mini';
import type {
  Queries as details_$name_page_EP_Queries,
  EntryPoints as details_$name_page_EP_EntryPoints,
  ExtraProps as details_$name_page_EP_ExtraProps,
  schema as details_$name_page_EP_schema,
  PreloadPropsHelpers as details_$name_page_EP_PreloadPropsHelpers,
} from './details_$name_page.entrypoint';
import type {
  Queries as hello_$name_page_EP_Queries,
  EntryPoints as hello_$name_page_EP_EntryPoints,
  ExtraProps as hello_$name_page_EP_ExtraProps,
  schema as hello_$name_page_EP_schema,
  PreloadPropsHelpers as hello_$name_page_EP_PreloadPropsHelpers,
} from './hello_$name_page.entrypoint';

declare global {
  type PastoriaRouteName = '/details/[name]' | '/hello/[name]';

  type PastoriaPageQueries = {
    ['/details/[name]']: details_$name_page_EP_Queries;
    ['/hello/[name]']: hello_$name_page_EP_Queries;
  };

  type PastoriaPageEntryPoints = {
    ['/details/[name]']: details_$name_page_EP_EntryPoints;
    ['/hello/[name]']: hello_$name_page_EP_EntryPoints;
  };

  type PastoriaPageExtraProps = {
    ['/details/[name]']: details_$name_page_EP_ExtraProps;
    ['/hello/[name]']: hello_$name_page_EP_ExtraProps;
  };

  type PastoriaPageProps<T extends PastoriaRouteName> = EntryPointProps<
    PastoriaPageQueries[T],
    PastoriaPageEntryPoints[T],
    {},
    PastoriaPageExtraProps[T]
  >;

  type PastoriaPreloadPropsParams = {
    ['/details/[name]']: z.output<typeof details_$name_page_EP_schema>;
    ['/hello/[name]']: z.output<typeof hello_$name_page_EP_schema>;
  };

  type PastoriaPreloadPropsHelpers = {
    ['/details/[name]']: details_$name_page_EP_PreloadPropsHelpers;
    ['/hello/[name]']: hello_$name_page_EP_PreloadPropsHelpers;
  };

  type GetPreloadProps<R extends PastoriaRouteName> = (
    params: PastoriaPreloadPropsHelpers[R],
  ) => PreloadProps<
    PastoriaPreloadPropsParams[R],
    PastoriaPageQueries[R],
    PastoriaPageEntryPoints[R],
    {}
  >;

  type ModuleParams<T extends PastoriaRouteName> =
    PastoriaPreloadPropsParams[T];
}
