import {createHash} from 'node:crypto';
import * as prettier from 'prettier';
import {SourceFile} from 'ts-morph';

/**
 * Regex to extract the checksum from a generated file's header comment.
 * Matches: @generated-checksum <hex-hash>
 */
const CHECKSUM_REGEX = /@generated-checksum ([a-f0-9]+)/;

/**
 * Regex to extract the raw (pre-formatting) checksum from a generated file's header comment.
 * Matches: @generated-raw-checksum <hex-hash>
 */
const RAW_CHECKSUM_REGEX = /@generated-raw-checksum ([a-f0-9]+)/;

/**
 * Computes a SHA-256 checksum of the given content.
 */
function computeChecksum(content: string): string {
  return createHash('sha256').update(content).digest('hex');
}

/**
 * Extracts the checksum from a file's content, if present.
 */
function extractChecksum(content: string): string | null {
  const match = content.match(CHECKSUM_REGEX);
  return match?.[1] ?? null;
}

/**
 * Extracts the raw (pre-formatting) checksum from a file's content, if present.
 */
function extractRawChecksum(content: string): string | null {
  const match = content.match(RAW_CHECKSUM_REGEX);
  return match?.[1] ?? null;
}

/**
 * Saves a source file to disk only if its content has changed.
 * Adds a checksum to the file header to enable fast comparison on subsequent runs.
 * Returns true if the file was written, false if skipped due to unchanged content.
 */
export async function saveWithChecksum(
  sourceFile: SourceFile,
): Promise<boolean> {
  const filePath = sourceFile.getFilePath();

  // Get the generated content (without checksum line yet)
  const rawGeneratedContent = sourceFile.getFullText();

  // Compute a raw checksum first to do a quick comparison before expensive formatting.
  // This avoids running Prettier when the underlying content hasn't changed.
  const rawChecksum = computeChecksum(rawGeneratedContent);

  // Try to read the existing file and extract its checksums
  let existingChecksum: string | null = null;
  let existingRawChecksum: string | null = null;
  try {
    const existingContent = await sourceFile
      .getProject()
      .getFileSystem()
      .readFile(filePath);
    existingChecksum = extractChecksum(existingContent);
    existingRawChecksum = extractRawChecksum(existingContent);
  } catch {
    // File doesn't exist yet, will need to write
  }

  // Fast path: if raw content hasn't changed, skip formatting entirely
  if (existingRawChecksum === rawChecksum && existingChecksum != null) {
    return false;
  }

  // Content changed — format with Prettier
  const generatedContent = await prettier.format(rawGeneratedContent, {
    parser: 'typescript',
    singleQuote: true,
  });

  // Compute checksum of formatted content
  const newChecksum = computeChecksum(generatedContent);

  // If formatted checksums match, skip writing
  if (existingChecksum === newChecksum) {
    return false;
  }

  // Insert both checksums into the header comment
  const contentWithChecksum = generatedContent.replace(
    '* This file was generated by `pastoria`.',
    `* This file was generated by \`pastoria\`.\n * @generated-checksum ${newChecksum}\n * @generated-raw-checksum ${rawChecksum}`,
  );

  // Update the source file content and save
  sourceFile.replaceWithText(contentWithChecksum);
  await sourceFile.save();

  return true;
}
