import babel from '@rolldown/plugin-babel';
import stylexPluginImport from '@stylexjs/unplugin/vite';
import react, {reactCompilerPreset} from '@vitejs/plugin-react';
import cookieParser from 'cookie-parser';
import express from 'express';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {IndentationText, Project} from 'ts-morph';
import {type Manifest, type Plugin, type ViteDevServer} from 'vite';
import {cjsInterop} from 'vite-plugin-cjs-interop';
import {PastoriaExecutionContext} from './generate.js';
import {logger, logInfo} from './logger.js';
import {createHandler} from '@pastoria/server';
import dotenv from 'dotenv';

const stylex =
  stylexPluginImport as unknown as (typeof stylexPluginImport)['default'];

type ViteMode = 'development' | 'production';

export function pastoria(): Plugin[] {
  return [
    pastoriaEntryPlugin(),
    stylex({useCSSLayers: true}),
    react(),
    babel({
      presets: [reactCompilerPreset()],
      plugins: [['relay']],
    }),
    cjsInterop({
      dependencies: ['react-relay', 'react-relay/hooks', 'relay-runtime'],
    }),
  ];
}

function pastoriaEntryPlugin(): Plugin {
  const clientEntryModuleId = 'virtual:pastoria-entry-client.tsx';
  const serverEntryModuleId = 'virtual:pastoria-entry-server.tsx';
  const project = new Project({
    tsConfigFilePath: path.join(process.cwd(), 'tsconfig.json'),
    manipulationSettings: {
      indentationText: IndentationText.TwoSpaces,
    },
  });

  let mode: ViteMode = 'development';
  let shouldGenerateOnBuildStart = false;

  return {
    name: 'pastoria',
    config() {
      return {
        appType: 'custom' as const,
        builder: {},
        customLogger: logger,
        build: {
          assetsInlineLimit: 0,
          manifest: true,
          ssrManifest: true,
          outDir: 'dist/client',
          rollupOptions: {
            input: 'virtual:pastoria-entry-client.tsx',
          },
        },
        ssr: {
          noExternal: ['@pastoria/runtime'],
        },
        environments: {
          ssr: {
            build: {
              outDir: 'dist/server',
              ssr: true,
              rollupOptions: {
                input: 'virtual:pastoria-entry-server.tsx',
              },
            },
          },
        },
      };
    },
    configResolved(config) {
      if (config.mode === 'production') {
        mode = 'production';
      }

      if (config.command === 'serve') {
        shouldGenerateOnBuildStart = true;
      }
    },
    configureServer(server) {
      return () => {
        server.middlewares.use(
          express()
            .use(cookieParser())
            .use(createPastoriaDevRouteHandler(server)),
        );
      };
    },
    async configurePreviewServer(server) {
      dotenv.config();

      const app = express()
        .use(cookieParser())
        .use(await createHandler());

      server.middlewares.use(app);
    },
    resolveId(id) {
      if (id === clientEntryModuleId) {
        return clientEntryModuleId; // Return without \0 prefix so React plugin can see .tsx extension
      } else if (id === serverEntryModuleId) {
        return serverEntryModuleId;
      }
    },
    async load(id) {
      if (id === clientEntryModuleId) {
        return generateClientEntry(mode);
      } else if (id === serverEntryModuleId) {
        return generateServerEntry();
      }
    },
    async buildStart() {
      if (!shouldGenerateOnBuildStart) {
        return;
      }

      logInfo('Updating generated files');
      await new PastoriaExecutionContext(project).generatePastoriaArtifacts();
    },
    async watchChange(id, {event}) {
      if (!id.match(/.tsx$/) || id.includes('__generated__')) return;

      if (event === 'create') {
        project.addSourceFileAtPath(id);
      } else if (event === 'delete') {
        project.getSourceFile(id)?.forget();
      } else if (event === 'update') {
        await project.getSourceFile(id)?.refreshFromFileSystem();
      }

      logInfo('Updating generated files');
      await new PastoriaExecutionContext(project).generatePastoriaArtifacts();
    },
  };
}

interface ServerEntry {
  createHandler(
    this: void,
    persistedQueries: {
      [hash: string]: string;
    },
    manifest?: Manifest,
  ): express.Router;
}

function createPastoriaDevRouteHandler(
  viteServer: ViteDevServer,
): express.Handler {
  return async (req, res, next) => {
    const persistedQueries = JSON.parse(
      await readFile('__generated__/router/persisted_queries.json', 'utf-8'),
    );

    const {createHandler: createDevHander} = (await viteServer.ssrLoadModule(
      'virtual:pastoria-entry-server.tsx',
    )) as ServerEntry;

    const handler = createDevHander(persistedQueries);
    handler(req, res, next);
  };
}

function generateClientEntry(mode: ViteMode): string {
  return `// Generated by Pastoria.
${mode === 'development' ? `import '@vitejs/plugin-react/preamble';` : ''}
import {createRouterApp} from '#genfiles/router/router';
import App from '#pastoria/app';
import {hydrateRoot} from 'react-dom/client';

async function main() {
  const RouterApp = await createRouterApp();
  hydrateRoot(document, <RouterApp App={App} />);
}

main();
`;
}

function generateServerEntry(): string {
  return `// Generated by Pastoria.
import {JSResource} from '#genfiles/router/js_resource';
import {
  listRoutes,
  router__createAppFromEntryPoint,
  router__loadEntryPoint,
} from '#genfiles/router/router';
import {router as serverRouter} from '#genfiles/router/server';
import App from '#pastoria/app';
import environment from '#pastoria/environment';
import express from 'express';
import {createRouterHandler} from '@pastoria/runtime/server';
import type {Manifest} from 'vite';

export function createHandler(
  persistedQueries: Record<string, string>,
  manifest?: Manifest,
) {
  const routeHandler = createRouterHandler(
    listRoutes(),
    JSResource.srcOfModuleId,
    router__loadEntryPoint,
    router__createAppFromEntryPoint,
    App,
    environment,
    persistedQueries,
    manifest,
  );

  const router = express.Router();
  router.use(routeHandler);
  router.use(serverRouter)

  return router;
}
`;
}
