/*
 * This file was generated by `pastoria`.
 * @generated-checksum f70184050ef8167ac19b2e87f4de87ee1e59baf587f2a1967bafe72be1cdf0f3
 * Do not modify this file directly.
 */
import type {
  EntryPoints,
  Queries,
  ExtraProps,
} from '../../pastoria/hello/[name]/page';
import type {
  EntryPoint,
  ThinNestedEntryPointParams,
  ThinQueryParams,
} from 'react-relay/hooks';
import { z } from 'zod/v4-mini';
import { JSResource, ModuleType } from './js_resource';
import page_HelloQueryParameters from '#genfiles/queries/page_HelloQuery$parameters';
import type {
  page_HelloQuery,
  page_HelloQuery$variables,
} from '#genfiles/queries/page_HelloQuery.graphql';
import {
  entrypoint as hello_$name_results_entrypoint,
  schema as hello_$name_results_schema,
} from './hello_$name_results.entrypoint';
import {
  entrypoint as hello_$name_banner_entrypoint,
  schema as hello_$name_banner_schema,
} from './hello_$name_banner.entrypoint';

const schema = z.object({
  name: z.string(),
  q: z.nullish(z.string()),
});

const entrypoint: EntryPoint<
  ModuleType<'/hello/[name]'>,
  z.output<typeof schema>
> = {
  root: JSResource.fromModuleId('/hello/[name]'),
  getPreloadProps($variables) {
    return (({ queries, entryPoints, variables }) => {
      return {
        queries: {
          nameQuery: queries.nameQuery({ name: variables.name }),
        },
        entryPoints: {
          helloBanner: entryPoints.helloBanner({}),
          searchResults: entryPoints.searchResults({
            q: variables.q ?? undefined,
          }),
        },
        extraProps: {
          query: variables.q ?? '',
        },
      };
    })({
      variables: $variables,
      queries: {
        ['nameQuery']: (variables) => ({
          parameters: page_HelloQueryParameters,
          variables,
        }),
      },
      entryPoints: {
        ['searchResults']: (entryPointParams) => ({
          entryPoint: hello_$name_results_entrypoint,
          entryPointParams,
        }),
        ['helloBanner']: (entryPointParams) => ({
          entryPoint: hello_$name_banner_entrypoint,
          entryPointParams,
        }),
      },
    } satisfies PreloadPropsHelpers);
  },
};

type RuntimeProps = { pathname: string; searchParams: URLSearchParams };

type PreloadPropsHelpers = {
  variables: z.output<typeof schema>;
  queries: {
    nameQuery: (
      variables: page_HelloQuery$variables,
    ) => ThinQueryParams<page_HelloQuery>;
  };
  entryPoints: {
    searchResults: (
      entryPointParams: z.output<typeof hello_$name_results_schema>,
    ) => ThinNestedEntryPointParams<
      EntryPoint<
        ModuleType<'/hello/[name]#results'>,
        ModuleParams<'/hello/[name]#results'>
      >
    >;
    helloBanner: (
      entryPointParams: z.output<typeof hello_$name_banner_schema>,
    ) => ThinNestedEntryPointParams<
      EntryPoint<
        ModuleType<'/hello/[name]#banner'>,
        ModuleParams<'/hello/[name]#banner'>
      >
    >;
  };
};

export {
  entrypoint,
  schema,
  type EntryPoints,
  type Queries,
  type RuntimeProps,
  type ExtraProps,
  type PreloadPropsHelpers,
};
