/*
 * This file was generated by `pastoria`.
 * Do not modify this file directly.
 */

import express from 'express';
import route0 from "../../pastoria/hello/route";

export const router = express.Router();
router.use('/hello', route0);
