/*
 * This file was generated by `pastoria`.
 * Do not modify this file directly.
 *
 * Type definitions for filesystem-based routing.
 */

import type {EntryPoint, EntryPointComponent, EntryPointProps} from 'react-relay/hooks';


// Route type aliases - nested entry points (leaf nodes)


// Route type aliases - main pages
type RouteRoot = { queries: {}; entryPoints: {} };

/**
 * Map of route paths to their query types.
 * Nested entry points use the format: '/route#entryPointName'
 */
export interface PageQueryMap {
  '/': RouteRoot;
}

/**
 * Props type for a page component at the given route.
 * Uses EntryPointProps to transform raw query types to PreloadedQuery<...>.
 *
 * @example
 * ```typescript
 * // Main page
 * export default function BlogPosts({ queries }: PageProps<'/posts'>) {
 *   const data = usePreloadedQuery(query, queries.posts);
 * }
 *
 * // Nested entry point
 * export default function Sidebar({ queries }: PageProps<'/posts#sidebar'>) {
 *   const data = usePreloadedQuery(query, queries.sidebarData);
 * }
 * ```
 */
export type PageProps<R extends keyof PageQueryMap> = EntryPointProps<
  PageQueryMap[R]['queries'],
  PageQueryMap[R]['entryPoints'],
  {},
  {}
>;
