/*
 * This file was generated by `pastoria`.
 * Do not modify this file directly.
 *
 * Type definitions for filesystem-based routing.
 */

import type {EntryPointProps} from 'react-relay/hooks';


/**
 * Map of route paths to their raw query and entry point types.
 * These are the type parameters passed to EntryPointProps.
 */
export interface PageQueryMap {
  '/': { queries: {}; entryPoints: {} };
}

/**
 * Props type for a page component at the given route.
 * Uses EntryPointProps to transform raw query types to PreloadedQuery<...>.
 *
 * @example
 * ```typescript
 * export default function BlogPosts({ queries }: PageProps<'/posts'>) {
 *   const data = usePreloadedQuery(query, queries.posts);
 *   // ...
 * }
 * ```
 */
export type PageProps<R extends keyof PageQueryMap> = EntryPointProps<
  PageQueryMap[R]['queries'],
  PageQueryMap[R]['entryPoints'],
  {},
  {}
>;
